# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c7c70ed3f50b9b4cd01108cf9c4fae8300b29bdaead827bc530362d26f22f90509bfef371f3e098d7fa3af3be44a9a06742b808e24c07e2180bb02672d14905

test:
  secret_key_base: c0a5fc9719cc9ef1a9c187e37d52431a0e95419b964abfc205eaf17f7e54b966c3573ac5bf2a1d99ba28ea6c0c999495467ab1e8ef9a22307a7f33b78e60e91f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
